<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Productphone extends Model
{
    public $fillable = [
        'DeviceName'
        ,'Brand'
        ,'technology'
        ,'gprs'
        ,'edge'
        ,'announced'
        ,'status'
        ,'dimensions'
        ,'weight'
        ,'sim'
        ,'type'
        ,'size'
        ,'models'
        ,'resolution'
        ,'display_c'
        ,'card_slot'
        ,'loudspeaker_'
        ,'sound_c'
        ,'wlan'
        ,'bluetooth'
        ,'gps'
        ,'radio'
        ,'usb'
        ,'features_c'
        ,'battery_c'
        ,'colors'
        ,'sar_eu'
        ,'sensors'
        ,'cpu'
        ,'internal'
        ,'os'
        ,'body_c'
        ,'video'
        ,'speed'
        ,'network_c'
        ,'chipset'
        ,'features'
        ,'protection'
        ,'gpu'
        ,'loudspeaker'
        ,'audio_quality'
        ,'nfc'
        ,'camera'
        ,'display'
        ,'performance'
        ,'build'
        ,'price'
        ,'sar'
        ,'single'
        ,'dual_'
        ,'triple'
        ,'_2g_bands'
        ,'_3_5mm_jack_'
        ,'_3g_bands'
        ,'_4g_bands'
    ];
}
